### ISSUE TITLE
Logs give 6 planks

### ISSUE THREAD

**Issue by 20o** [Tfarcenim/WoodCutter#3]
Is this intentional?

**Comment by Tfarcenim** [comment]
yes, use a datapack if you don't like it

**Comment by 20o** [comment]
It's not that I don't like it (2 free planks lol) but the way the stonecutter works is that rather than giving _more_ it gives an amount that's _equivalent_ to what you put in, like how the crafting table recipe for stairs is 5 stone bricks but only gives 4 stairs,  whereas the stonecutter gives you 5 stairs for 5 bricks so shouldn't the woodcutter follow the same logic? @Tfarcenim
